[package]
org = "admin"
name = "back_end"
version = "0.1.0"
distribution = "2201.10.2"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.20"